import type { Metadata } from "next";
import { siteConfig } from "@/lib/site";

type MetaInput = {
  title: string;
  description: string;
  path?: string;
  /** Optional custom share image path (absolute or site-relative). Prefer 1200×630. */
  image?: string;
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
};

export function absoluteUrl(path = "/") {
  return new URL(path, siteConfig.domain).toString();
}

/** Default social share card — generated by app/opengraph-image.tsx (1200×630). */
export const defaultOgImage = {
  url: absoluteUrl("/opengraph-image"),
  width: 1200,
  height: 630,
  alt: `${siteConfig.brandName} — ${siteConfig.tagline}`,
  type: "image/png",
} as const;

export function buildMetadata({
  title,
  description,
  path = "/",
  image,
  type = "website",
  publishedTime,
  modifiedTime,
}: MetaInput): Metadata {
  const canonical = absoluteUrl(path);
  const ogImages = image
    ? [
        {
          url: image.startsWith("http") ? image : absoluteUrl(image),
          width: 1200,
          height: 630,
          alt: title,
        },
      ]
    : [defaultOgImage];

  const openGraph =
    type === "article"
      ? {
          title,
          description,
          url: canonical,
          siteName: siteConfig.name,
          locale: "en_US" as const,
          type: "article" as const,
          images: ogImages,
          publishedTime,
          modifiedTime: modifiedTime ?? publishedTime,
        }
      : {
          title,
          description,
          url: canonical,
          siteName: siteConfig.name,
          locale: "en_US" as const,
          type: "website" as const,
          images: ogImages,
        };

  return {
    title,
    description,
    applicationName: siteConfig.brandName,
    authors: [{ name: siteConfig.brandName }],
    creator: siteConfig.brandName,
    publisher: siteConfig.brandName,
    alternates: { canonical },
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true },
    },
    openGraph,
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ogImages.map((img) => img.url),
    },
  };
}

export function faqPageJsonLd(items: Array<{ q: string; a: string }>) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: { "@type": "Answer", text: item.a },
    })),
  };
}

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: siteConfig.brandName,
    alternateName: siteConfig.tagline,
    url: siteConfig.domain,
    logo: absoluteUrl("/brand-mark.png"),
    sameAs: [siteConfig.linkedInContactUrl],
  };
}

export function softwareJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: siteConfig.brandName,
    alternateName: siteConfig.tagline,
    applicationCategory: "MultimediaApplication",
    operatingSystem: "Android, iOS",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    downloadUrl: siteConfig.playStoreUrl,
    installUrl: [siteConfig.playStoreUrl, siteConfig.appStoreUrl],
  };
}

export function breadcrumbJsonLd(
  items: Array<{ name: string; path: string }>,
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}

export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteConfig.name,
    alternateName: [siteConfig.brandName, siteConfig.tagline],
    url: siteConfig.domain,
    description: siteConfig.description,
    publisher: {
      "@type": "Organization",
      name: siteConfig.brandName,
      logo: absoluteUrl("/brand-mark.png"),
    },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${siteConfig.domain}/blog?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };
}
